language: go

go:
- 1.4

sudo: required

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install: bin/travis-install.sh

script: go test -v zombiezen.com/go/capnproto/...
